# Build Stage
FROM debian:stable-slim AS builder
RUN apt-get update && apt-get install -y curl git unzip xz-utils zip libglu1-mesa
WORKDIR /sdk
RUN git clone https://github.com/flutter/flutter.git -b stable
ENV PATH="/sdk/flutter/bin:/sdk/flutter/bin/cache/dart-sdk/bin:${PATH}"
RUN flutter doctor

WORKDIR /app
COPY TeamOS-app/ .
RUN flutter pub get
RUN flutter build web --release

# Production Stage
FROM nginx:alpine
COPY --from=builder /app/build/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
